### ISSUE TITLE
BUG: Neotree reveal puts the selected node on top of the view

### ISSUE THREAD

**Issue by ghostbuster91** [nvim-neo-tree/neo-tree.nvim#1306]
### Did you check docs and existing issues?

- [X] I have read all the docs.
- [X] I have searched the existing issues.
- [X] I have searched the existing discussions.

### Neovim Version (nvim -v)

0.9.5

### Operating System / Version

nixos

### Describe the Bug

In some cases when I do `Neotree source=filesystem reveal=true position=left` the neotree view is scrolled down in a way that the selected node is put on top. If I move my cursor then to another window, the original position is restored. 

### Screenshots, Traceback

In this video I perform following actions:
1. put cursor on the main window
2. neotree reveal
3. cursor is put into the neotree window, the window is scrolled
4. move cursor back to the main window
5. neotree reveal
6. cursor is put into the neotree window, the window is scrolled

[Kooha-2024-01-13-12-32-03.webm](https://github.com/nvim-neo-tree/neo-tree.nvim/assets/5662622/5786ceb6-7813-45cd-b19c-36c95e709fa8)

### Steps to Reproduce

1. open a file in some project, in my case that was https://github.com/scalameta/nvim-metals (`vim  lua/metals/tvp/init.lua`) - the project might be relevant
2. call neotree reveal
3. go back to the file and hit GG to go to the bottom
4. call neotree reveal
5. go back to the file again
6. call neotree reval
7. observe that the neotree window has been scrolled

If I remove the `documentSymbol` source from the sources list the issue goes away.
**I was not able to reproduce it with the minimal config attached.** I think that the reproduction requires to have lsp for lua configured. I will try to provide config for local reproduction later. 

### Expected Behavior

I would expect the neotree position to stay intact when the selected node is visible on the window.

### Your Configuration

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  -- add any other plugins here
}

local neotree_config = {
  "nvim-neo-tree/neo-tree.nvim",
  dependencies = { "MunifTanjim/nui.nvim", "nvim-tree/nvim-web-devicons", "nvim-lua/plenary.nvim" },
  cmd = { "Neotree" },
  keys = {
    { "<Leader>e", "<Cmd>Neotree<CR>" }, -- change or remove this line if relevant.
  },
  opts = {
    sources = { "filesystem", "git_status", "buffers", "document_symbols" },
    -- Your config here
    -- ...
  },
}

table.insert(plugins, neotree_config)
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by georgeguimaraes** [comment]
I think @cseickel released 3.15 after your report here. Can you try it? I think the PRs included in 3.15 should fix this issue.

**Comment by ghostbuster91** [comment]
Indeed, I can no longer reproduce the issue this way. Sometimes it still happens though but I think that it is a different issue.

**Comment by ghostbuster91** [comment]
My bad, I must've not reloaded something correctly. The issue is still there.

**Comment by ghostbuster91** [comment]
Nvm, I somehow did commit version update and was using an older version, just tested on the newer one and the issue is no longer there. Sorry for the spam.
