### ISSUE TITLE
`filter.respect_gitignore = true` seems not working on WindowsOS

### ISSUE THREAD

**Issue by lopi-py** [nvim-neo-tree/neo-tree.nvim#158]
also when I set `filter.show_hidden = false` my `.gitignore` doesn't render, is this intended?
Edit: I did notice that just not works with directories

**Comment by cseickel** [comment]
> Edit: I did notice that just not works with directories

I don't use neovim on Windows, so I can only guess at the problem, but that is a good clue. I'll take a look.


> also when I set `filter.show_hidden = false` my `.gitignore` doesn't render, is this intended?

Yes, because the "hidden" files logic is actually using the *nix convention of files that start with a dot are hidden. It does not actually support the Windows version of what is a hidden folder.

**Comment by cseickel** [comment]
There was a bug I fixed with gitignore not working for directories recently. Can you confirm that you are on the latest release and whether you have set the `gitignore_source = "git check-ignore"` option?

**Comment by lopi-py** [comment]
yes, I'm on the latest release, also when I set `gitignore_source = "git check-ignore"` also not works with files, since I'm on Windows I'll try to look into it and fix it

**Comment by nyngwang** [comment]
@lopi-py: Joke aside, you missed the `s`. It's `filters.respect_gitignore = true`.
