### ISSUE TITLE
Invalid buffer on startup

### ISSUE THREAD

**Issue by lispyclouds** [nvim-neo-tree/neo-tree.nvim#340]
Since pulling in the recent changes, I'm seeing this now when starting nvim:
```
[neo-tree.nvim] [ERROR 07:37:08] ...k/packer/opt/neo-tree.nvim/lua/neo-tree/events/queue.lua:146: Error in event handler for event vim_buffer_enter[filesystem.vim_buffer_enter]: ...ite/pack/pa
cker/opt/neo-tree.nvim/lua/neo-tree/utils.lua:337: Invalid buffer id: -1 
```
Is there something I should be changing? These are my current settings: https://github.com/lispyclouds/dotfiles/blob/main/nvim/fnl/plugins.fnl#L18-L21

Thanks for building this! 😄

**Comment by lispyclouds** [comment]
I think this started since https://github.com/nvim-neo-tree/neo-tree.nvim/commit/6f12619b47037bd5b555c824c6df665dcef56362

**Comment by idanarye** [comment]
This error can also be seen when closing a terminal

**Comment by cseickel** [comment]
I'm not getting the error but I can see what might be causing it and I pushed a fix to `main`. Can you try it out and let me know if this fixes it?

**Comment by idanarye** [comment]
(not OP, but getting the same error)
I no longer get the error when I start Neovim, but it still shows when a close a terminal.

**Comment by cseickel** [comment]
@idanarye Can you tell me what command you are using to close the terminal, and if you are using any terminal related plugins? Is it in a floating window?

**Comment by lispyclouds** [comment]
Seems to be fixed for me! I don't seem to have the terminal issue. Thanks a lot for the quick fix! 😄

**Comment by idanarye** [comment]
@cseickel I open the terminal with `:terminal` and close it with `C-d` (while in terminal mode).

I tried running a setup with just neo-tree (and it's mandatory dependencies, plenary and nui) and a blank neo-tree configuration (just `require'neo-tree'.setup()`), and still got that error message.

**Comment by cseickel** [comment]
> I open the terminal with `:terminal` and close it with `C-d` (while in terminal mode).

I don't believe I never tried exiting a terminal with `C-d`! 🤯  Here I was exiting terminal mode and then `:q` all this time, what a waste of keystrokes!

I still don't get the error though. Can you copy the current error message here so I can see what line it is hitting now?

**Comment by cseickel** [comment]
Sorry about the auto close from the release. It's re-opened now.

**Comment by idanarye** [comment]
It looks like 02b3267d4f7d14482a2af6263965da601f5bcf1a fixed the issue, but before the the error message was:

```
[neo-tree.nvim] [ERROR 18:48:38] ./neo-tree.nvim/lua/neo-tree/events/queue.lua:146: Error in event handler for event vim_buffer_deleted[buffers.vim_buffer_deleted]: ./neo-tree.nvim/lua/neo-tree/utils.lua:337: Invalid buffer id: -1
```

**Comment by cseickel** [comment]
> It looks like [02b3267](https://github.com/nvim-neo-tree/neo-tree.nvim/commit/02b3267d4f7d14482a2af6263965da601f5bcf1a) fixed the issue

That's good. In that case I'll close the issue.
