### ISSUE TITLE
Commit message on windows is not allowed to contain space.

### ISSUE THREAD

**Issue by dhammena** [nvim-neo-tree/neo-tree.nvim#484]
One word is ok.

Error when contain space.

e.g "test fterm"
![Screenshot (14)](https://user-images.githubusercontent.com/8435488/184610960-b617b5df-a1fa-46d7-a5ac-a748bd572b8f.png)

**Comment by cseickel** [comment]
This was originally written with string templates executed by the local shell, but it should be converted to a table (list) of arguments to avoid differences in how strings are quoted or escaped.

I'll do this soon, but I'll have to rely on you to test it and confirm it works because I don't have a windows computer handy right now.

**Comment by dhammena** [comment]
> This was originally written with string templates executed by the local shell, but it should be converted to a table (list) of arguments to avoid differences in how strings are quoted or escaped.
> 
> I'll do this soon, but I'll have to rely on you to test it and confirm it works because I don't have a windows computer handy right now.

Ok！ This plugin is of high quality and works well. Thank you for your excellent work！

**Comment by cseickel** [comment]
> This plugin is of high quality and works well. Thank you for your excellent work！

You're very welcome!

I think this is fixed in the `main` branch right now. Can you give it a try and let me know if it works for you?

**Comment by dhammena** [comment]
The bug isn't fixed, although i have reinstalled the package.

**Comment by cseickel** [comment]
> The bug isn't fixed, although i have reinstalled the package.

To be clear, you didn't need tlol reinstall, just switch your branch from the recommended `v2.x` to `main` and then source the file or restart nvim and run `:PackerSync` (if you use Packer.)

**Comment by dhammena** [comment]
Sorry for my carelessness.
The bug have fixed after switch branch from v2.x to main. 
Thanks again.

**Comment by cseickel** [comment]
Thanks for confirming. This has been released to `v2.x`, you can switch back to that stable branch now if you want.
