### ISSUE TITLE
Feature request: add highlight for open files

### ISSUE THREAD

**Issue by serhez** [nvim-neo-tree/neo-tree.nvim#743]
It would be nice to have a highlight for files which are open in existing buffers. This is a nvim-tree feature which I miss having.

**Comment by miversen33** [comment]
To be clear, this request is for _more_ than simply having the cursorline on the file that is open, correct? That is already something that Neo-tree supports, so I want to be sure this is an ask that is not already solved via configuration :)

**Comment by serhez** [comment]
Hey @miversen33 ! Thanks for the reply. No, I don't mean just having automatic cursor positioning over the line of the currently open file. I mean that every file on the tree which is currently open in some buffer would be highlighted differently from other files.

Here is an example of how it looks in `nvim-tree` (the highlighting group can be changed of course):
![Screenshot 2023-02-14 at 21 03 16](https://user-images.githubusercontent.com/18057093/218832631-3cd3ae1f-cff5-43a7-ac43-a268c28f21ea.jpg)

**Comment by nhat-vo** [comment]
@serhez The highlight open files feature that you requested has been merged in #838. Have a look to see if it matches your expectation 😁.

**Comment by serhez** [comment]
Hey @nhat-vo, thanks so much! Unfortunately, I can't seem to get it working. I updated the plugin to the latest commit and have added the following snippet to my config, but I don't get any highlighting on open files, maybe I'm missing something?

```lua
default_component_configs = {
  name = {
    highlight_opened_files = true,
  },
},
```

**Comment by miversen33** [comment]
I am not able to get this functioning either. Instead, I am noticing the file names that are opened are being italicized?

![image](https://user-images.githubusercontent.com/2640668/230749070-78c7295a-2134-4189-be18-2c67ee74ca86.png)


My config for this
```lua
default_component_configs = {
    name = {
        highlight_opened_files = true
    }
}
```

**Comment by nhat-vo** [comment]
@serhez @miversen33 That's odd... Could you check the value of the highlight group `NeoTreeFileNameOpened`?

**Comment by serhez** [comment]
The highlight group exists but it's defined to be the same as `Normal`, additionally with `gui=bold`.

**Comment by nhat-vo** [comment]
@serhez That is the group that is used to highlight the opened files. What happens when you set it to some other value (maybe changing the fg/bg)?

**Comment by serhez** [comment]
I'm not familiar with your code base, but maybe `highlights.lua:245` is the culprit?

```lua
M.create_highlight_group(M.FILE_NAME_OPENED, {}, nil, nil, "bold")
```

**Comment by serhez** [comment]
By changing the highlight group I get it working, but I saw another problem, which is that if I restore a session (quit Neovim and open it again), the buffers which are open but I have not read yet are not identified as "opened" by neo-tree. This is probably because you have some callback on the `BufRead` event or similar to highlight the buffer as "opened"; maybe an initial scan of existing buffers would solve this?

![Screenshot 2023-04-09 at 12 34 56](https://user-images.githubusercontent.com/18057093/230765580-95328d4a-ebdb-4dc0-8131-6f00cf9515fd.jpg)

**Comment by nhat-vo** [comment]
@serhez Great! My guess was that the highlight used to be bold, which is suppressed by your terminal. 

Regarding the problem with sessions, the current behavior mimics the `buffer` source with `show_unloaded = false` as mentioned [here](https://github.com/nvim-neo-tree/neo-tree.nvim/blob/2b2f74828eeb02cf29d6b21aa32eedadadc94ca7/README.md?plain=1#L308).
I've just pushed an additional config in #856. You can set `highlight_opened_files = all` to show all buffers, both loaded and unloaded. Have a look to see if it fixes your problem.

**Comment by serhez** [comment]
@nhat-vo since this has not been merged yet to main, I tried your branch and the problem is solved there. However, I have observed that there are some files being highlighted which are not open in any buffer, which seems strange (I've confirmed this beyond the bufferline by listing all open buffers). Below is a screenshot, notice that `cmp.lua` is highlighted but it's not open.

![Screenshot 2023-04-10 at 01 01 41](https://user-images.githubusercontent.com/18057093/230798576-5a43716e-d03e-44c9-b76c-3e559ccbbddc.jpg)

**Comment by nhat-vo** [comment]
@serhez my bad. I made a mistake with `vim.fn.buflisted` command. Should work fine now, have a look 😅

**Comment by miversen33** [comment]
I am still not able to get this working on my setup :upside_down_face: 

Below is a minimal config that I am testing with (you can use the config to test as well if you like, it creates a whole new temp directory to run the neovim instance from so its effectively clean)

```lua
-- Minimal configuration
-- mini.lua
-- Use with the --clean -u flags. EG nvim --clean -u mini.lua
-- This config will create a temp directory and will blow away that temp directory
-- everytime this configuration is loaded. Great for simulating a new installation
-- of a plugin

local sep = vim.loop.os_uname().sysname:lower():match('windows') and '\\' or '/' -- \ for windows, mac and linux both use \

local mod_path = string.format("%s%sneo-tree-test%s", vim.fn.stdpath('cache'), sep, sep)
if vim.loop.fs_stat(mod_path) then
    -- Clearing out the mods directory and recreating it so 
    -- you have a fresh run everytime
    vim.fn.delete(mod_path, 'rf')
end

vim.fn.mkdir(mod_path, 'p')

local modules = {
    {'nvim-lua/plenary.nvim'},
    {'nvim-tree/nvim-web-devicons'},
    {'MunifTanjim/nui.nvim'},
    -- 'nvim-neo-tree/neo-tree.nvim'
    {'nhat-vo/neo-tree.nvim', branch = '743-hl-open-files'},
}
for _, module in ipairs(modules) do
    local repo = module[1]
    local branch = module.branch
    local module_name = repo:match('/(.*)')
    local module_path = string.format('%s%s%s', mod_path, sep, module_name)
    if not vim.loop.fs_stat(module_name) then
        -- The module doesn't exist, download it
        local cmd = {
            'git',
            'clone'
        }
        if branch then
            table.insert(cmd, '--branch')
            table.insert(cmd, branch)
        end
        table.insert(cmd, string.format('https://github.com/%s', repo))
        table.insert(cmd, module_path)
        vim.fn.system(cmd)
        print(string.format("Downloaded %s", module_name))
    end
    vim.opt.runtimepath:append(module_path)
end

-- We should be able to safely assume everything exists and is pathed correctly
local loaded, neo_tree = pcall(require, 'neo-tree')
if not loaded then
    vim.notify('Unable to load neo-tree!', vim.log.levels.ERROR)
    return
end

-- Setting up neo-tree
neo_tree.setup({
    default_component_configs = {
        name = {
            highlight_opened_files = true,
        }
    }
})
print("Loaded Neotree!")
```

**Comment by nhat-vo** [comment]
@serhez I don't have my laptop with me, but you need to put `highlight_opened_files = "all"` instead of `true`. I'll test out your config later.

**Comment by miversen33** [comment]
@nhat-vo wrong person ;)
But ya using that option is no more effective than what I had before

**Comment by nhat-vo** [comment]
@miversen33 Seems that the config is not using `termguicolors`. Adding `vim.opt.termguicolors = true` works for me. In the screenshot `CONTRIBUTING.md`, `README.md`, and `mini.lua` are open, and are highlighted as `gui=bold`.

![image](https://user-images.githubusercontent.com/30724347/231003692-9829a8cd-684f-427f-ac0b-c2e8d88ba9d0.png)

If you are using TUI highlight groups or your terminal suppresses bold fonts, you can modify the `NeoTreeFileNameOpened` hl group (I also tried `:hi NeoTreeFileNameOpened ctermfg=11` without setting `termguicolors`, and it works as wel).

**Comment by miversen33** [comment]
Ahh so the "highlight" in this case is the font being bold! I always forget that "highlight" in vim is more "text formatting" than simply changing the background color of the text.

I do see it being bold in my actual config (I forgot to add it in my minimal config, whoops), I just assumed that was incorrect behavior based on my misassumption of "highlight". Is there a plan to allow configuring the "NeoTreeFileNameOpened" group via the neo-tree configuration, or are we going to recommend manually modifying the `hl group` in your vim config?

**Comment by nhat-vo** [comment]
Glad that it worked! I think generally these hl group configs are not exposed in the setup. Rather, users can set the hl group themselves manually through `:hi` and friends. I think this is the general design of neo-tree and most other plugins I have seen.

**Comment by lpuljic** [comment]
Hi, sorry to ask the question in a closed issue. 

Is it possible when I close the  file with `:q` to not stay highlighted,  the only time I can get this to clear highlighting of a open file is if I delete the buffer `:bd`
